version: "2.4"

services:
  mal-db-api:
    container_name: mal-db-api
    image: mal-db:latest
    command: /mal server
    build:
      context: ./..
      dockerfile: ./build/package/Dockerfile
    ports:
      - 8006:8006
    tty: true
    env_file: ./../.env
    depends_on:
      - mal-db-worker
  mal-db-worker:
    container_name: mal-db-worker
    image: mal-db:latest
    command: /mal worker
    build:
      context: ./..
      dockerfile: ./build/package/Dockerfile
    tty: true
    env_file: ./../.env