version: "2.4"

services:
  mal-db-install:
    container_name: mal-db-install
    image: mal-db:latest
    command: /mal install
    build:
      context: ./..
      dockerfile: ./build/package/Dockerfile
    tty: true
    env_file: ./../.env